Module4 tasks
Nastya-Korsak/.Net-Mentoring-Program pull request #3
Opened 2021-04-14 18:40 UTC by Nastya-Korsak

Task1 and Task2

2021-04-17 23:47 UTC, alexander-trishin requested changes
Hi Nastya,

Unfortunately, I found a few bugs. Please change the code according to my comments.

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +            items.Should().BeEquivalentTo(@"d:\test1\tes1_1", @"d:\test1\tes1_2");
Here is a bug in the `FileSystemVisitor` class. `FilteredFileFound` should be fired only for files with `.txt` extension. So the final result should be:
```
d:\test1\im.gif
d:\test1\test1_1
d:\test1\test1_2
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +            items.Select(i => i.Substring(i.LastIndexOf('\\'))).Should().NotContain("test");
You're reinventing the wheel here 😃 

```suggestion
            items.Select(info => new DirectoryInfo(info).Name).Should().NotContain("test");
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +        public void Search_NullPath_ArgumentNullException()
```suggestion
        public void Search_PathParameterIsNull_ShouldThrowArgumentNullException()
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +                .And.ParamName.Should().Be(null);
`ParamName` should never be `null`. It's a bug in `FileSystemVisitor`.

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/Actions.cs
> +    public enum Actions
Please use more unique names for top-level elements like classes, interfaces and enums.

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +        private readonly Func<FileSystemInfo, bool> _filterFunc;
It's clear that this is a `Func` when we look at the type of the variable.

```suggestion
        private readonly Func<FileSystemInfo, bool> _filter;
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +            _fileSystem = fileSystem;
File system is a critical dependency for this class. Incorrect behavior should be prevented as soon as possible.
```suggestion
            _fileSystem = fileSystem ?? throw new ArgumentNullException(nameof(fileSystem));
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +        public event Action Complited;
A typo.

```suggestion
        public event Action Completed;
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +        public event Func<FileSystemInfo, Actions> FileFound;
Normally event handlers should match `EventHandler` syntax. [MSDN Guide for events](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-publish-events-that-conform-to-net-framework-guidelines).

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                throw new ArgumentNullException(path, "Directory path is null");
Should be:
```suggestion
                throw new ArgumentNullException(nameof(path));
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                throw new ArgumentException("Directory path is empty", path);
Please, do not forget to use `nameof` keyword.

```suggestion
                throw new ArgumentException("Directory path is empty", nameof(path));
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                throw new ArgumentException("Selected directory is not exist", path);
Try to always use more specific types of exceptions:

```suggestion
                throw new DirectoryNotFoundException($"Selected directory is not exist: {path}");
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +            foreach (var d in DirectionSearch(path))
The recursive algorithm is more applicable for this task. It should also fix the bug where directories are listed only after files.

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +        private IEnumerable<string> FileSearch(string path)
I would recommend to work with `FileSystemInfo` class.

```suggestion
        private IEnumerable<string> FileSearch(FileSystemInfo fileInfo)
```

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +            foreach (var f in _fileSystem.Directory.EnumerateFiles(path).Where(f => _filterFunc == null || !_filterFunc(new FileInfo(f))))
Short names are only applicable in rare cases.

For example: `directories.Select(x => x.Name)` The lambda is pretty small and still readable.

As the method body increases, short names become unreadable.

2021-04-17 23:47 UTC, alexander-trishin commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                    _action = FilteredFileFound.Invoke(fileInfo);
[Bug] It will mark normal files as filtered (because of rows #74 and #82)

2021-04-18 17:06 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +    public class UnitTest1
fixed

2021-04-18 17:06 UTC, Nastya-Korsak commented on Module_4/Task1/Task1.sln
> +﻿
fixed

2021-04-18 17:06 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +            items.Should().BeEquivalentTo(@"d:\test1\im.gif", @"d:\test1\tes1_1\text.txt", @"d:\test1\tes1_2\text2.txt", @"d:\test1\tes1_1", @"d:\test1\tes1_2");
fixed

2021-04-18 17:06 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +            var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
fixed

2021-04-18 17:06 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary.Tests/UnitTest1.cs
> +                if (e.Name.Contains("tes1_1"))
fixed

2021-04-18 17:07 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                throw new ArgumentException("Selected directory is not exist", path);
fixed

2021-04-18 17:07 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +            foreach (var d in DirectionSearch(path))
fixed

2021-04-18 17:07 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +        private IEnumerable<string> FileSearch(string path)
fixed

2021-04-18 17:07 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +            foreach (var f in _fileSystem.Directory.EnumerateFiles(path).Where(f => _filterFunc == null || !_filterFunc(new FileInfo(f))))
fixed

2021-04-18 17:07 UTC, Nastya-Korsak commented on Module_4/FileSystemVisitorLibrary/FileSystemVisitor.cs
> +                    _action = FilteredFileFound.Invoke(fileInfo);
fixed

2021-04-19 18:34 UTC, alexander-trishin approved these changes
I see a few typos, but in general: good job! 😄

2021-04-20 06:47 UTC, merged