Module5 tasks
Nastya-Korsak/.Net-Mentoring-Program pull request #4
Opened 2021-04-20 19:02 UTC by Nastya-Korsak

Module 5, Tasks 1,2,3

2021-04-26 22:31 UTC, alexander-trishin requested changes
Hi Nastya 😃

Unfortunately, I've found a few issues. Please, fix them and let me know when its ready

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task1/Task1.csproj
> +    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="13.2.28" />
Copy-pasted from the previous module :)

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task2/NumberParser.cs
> +            if (!int.TryParse(stringValue, out var result))
The task requires not to use such methods as `int.Parse` or `int.TryParse`. Please, fix this method

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task2/NumberParser.cs
> +            if (char.IsDigit(stringValue.First()) || stringValue.First() == '-')
You could use RegExp here. It should be much simplier than current version

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task3/UserTaskController.cs
> +            _taskService = taskService;
Please, add check for null value here and throw `ArgumentNullException` if needed

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task3/UserTaskController.cs
> +                model.AddAttribute("action_result", message);
Possible null reference exception here

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task3/UserTaskService.cs
> +                throw new ArgumentOutOfRangeException(message: "Invalid userId", null);
Always specify `paramName` for any `Argument*` exception

2021-04-26 22:31 UTC, alexander-trishin commented on Module_5/ExceptionHandling/Task3/UserTaskService.cs
> +                throw new ArgumentNullException(message: "User not found", null);
Incorrect exception type. `user` is a local variables but used as an argument of the method.

2021-04-27 06:39 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task2/NumberParser.cs
> +            if (!int.TryParse(stringValue, out var result))
Task says that we can use int.Parse and int.TryParse but not other built-in methods 
![image](https://user-images.githubusercontent.com/48296970/116196677-7b185280-a73c-11eb-9ec0-0cae68831f9f.png)

2021-04-27 06:46 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task3/UserTaskService.cs
> +                throw new ArgumentOutOfRangeException(message: "Invalid userId", null);
I can't do it in this place because of Unit Tests. Test expects only a message to be sent 'Invalid userId'. If I will ad paramName it will be added in message and Unit Test will fail

2021-04-27 07:04 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task3/UserTaskController.cs
> +                model.AddAttribute("action_result", message);
I think this is an unnecessary action, because this message is an exception message, and if it is null, then the program passed without errors.

2021-04-27 11:49 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task1/Task1.csproj
> +    <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="13.2.28" />
Fixed

2021-04-27 11:49 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task2/NumberParser.cs
> +            if (!int.TryParse(stringValue, out var result))
Fixed

2021-04-27 11:49 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task2/NumberParser.cs
> +            if (char.IsDigit(stringValue.First()) || stringValue.First() == '-')
Fixed

2021-04-27 11:50 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task3/UserTaskController.cs
> +            _taskService = taskService;
Fixed

2021-04-27 11:50 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task3/UserTaskController.cs
> +                model.AddAttribute("action_result", message);
Fixed

2021-04-27 11:50 UTC, Nastya-Korsak commented on Module_5/ExceptionHandling/Task3/UserTaskService.cs
> +                throw new ArgumentNullException(message: "User not found", null);
Fixed

2021-04-29 19:32 UTC, alexander-trishin approved these changes
Good job! 😄

2021-04-30 08:41 UTC, merged