Module 7
Nastya-Korsak/.Net-Mentoring-Program pull request #6
Opened 2021-05-06 18:30 UTC by Nastya-Korsak

Module 7, Reflection

2021-05-24 20:17 UTC, alexander-trishin requested changes
Hi Nastya,

Good work, we're almost good to go :)

2021-05-24 20:17 UTC, alexander-trishin commented on Module_7/Reflection/Task1/Container.cs
> +                .ForEach(t => AddType(t));
Please, use `foreach` keyword. `ForEach` method is obsolete (comes from dotnet when there was no `IEnumerable`)

2021-05-24 20:17 UTC, alexander-trishin commented on Module_7/Reflection/Task1/Container.cs
> +                .Single(t => t.Key == true)
Please, use `SingleOrDefault` or `FirstOrDefault`

2021-05-24 20:17 UTC, alexander-trishin commented on Module_7/Reflection/Task1/Container.cs
> +                throw new DuplicateWaitObjectException(nameof(assembly), "This assembly is already added");
```suggestion
                throw new ArgumentException(nameof(assembly), "This assembly is already added");
```

2021-05-25 14:31 UTC, Nastya-Korsak commented on Module_7/Reflection/Task1/Container.cs
> +                throw new DuplicateWaitObjectException(nameof(assembly), "This assembly is already added");
fixed

2021-05-25 14:35 UTC, Nastya-Korsak commented on Module_7/Reflection/Task1/Container.cs
> +                .Single(t => t.Key == true)
I added an if condition to check that the typesWithExportAttribute contains the required key, so now I think it is unnecessary

2021-05-25 14:42 UTC, Nastya-Korsak commented on Module_7/Reflection/Task1/Container.cs
> +                .ForEach(t => AddType(t));
fixed

2021-05-26 14:48 UTC, alexander-trishin approved these changes

2021-05-27 07:24 UTC, merged